server:
  port: ${SERVER_PORT:0}

spring:
  application:
    name: pp-order-persistence
  main:
    lazy-initialization: false
    banner-mode: "off"
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    default-property-inclusion: USE_DEFAULTS
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://admin:123456@localhost:27017}
      database: local
  kafka:
    bootstrap-servers-id: ${BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: order-persistence-group-id
      listener-id: order-persistence-listener-id
      topic-order: ${TOPIC_ORDER:order-persistence}
      max-poll-records: ${KAFKA_MAX_POLL_RECORDS:1}
      concurrency: ${KAFKA_CONCURRENCY:1}
      key-deserializer: "org.apache.kafka.common.serialization.IntegerDeserializer"
      value-deserializer: "org.springframework.kafka.support.serializer.JsonDeserializer"
      properties:
        spring:
          json:
            value:
              default:
                type: "br.com.vnrg.pporderstream.model.Order"
            trusted:
              packages: "br.com.vnrg"
logging:
  level:
    root: ${LOG_LEVEL:info}
    org.springframework: error
    org.apache: error